AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rspec
  - rubocop-rake

RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
